/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chance;

import org.junit.Before;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class ChanceTest {
    private Chance testChance;
    private Chance anotherChance;

    @Before
    public void setUp() throws Exception {
        testChance = new Chance(0.4D);
        anotherChance = new Chance(0.3D);
    }

    @Test
    public void should_get_and_method_result() {
        //given
        //when
        //then
        assertThat(testChance.and(anotherChance)).isEqualToComparingFieldByField(new Chance(0.12D));
    }

    @Test
    public void should_get_or_method_result() {
        //given
        //when
        //then
        assertThat(testChance.or(anotherChance)).isEqualToComparingFieldByField(new Chance(0.58D));
    }


    @Test
    public void should_get_not_method_result() {
        //given
        //when
        //then
        assertThat(testChance.not()).isEqualToComparingFieldByField(new Chance(0.6D));
    }
}
