/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chance;

public class chance {
    private Double fraction;

    public chance(Double fraction) {
        this.fraction = fraction;
    }

    public Double getFraction() {
        return fraction;
    }

    public chance and(chance anotherchance) {
        return new chance(fraction * anotherchance.getFraction());
    }

    public chance or(chance anotherchance) {
        Double orResult = fraction + anotherchance.getFraction();
        return new chance(orResult > 1.0d ? 1.0d : orResult);
    }

    public chance not() {
        return new chance(1 - fraction);
    }
}
