/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chance;

public class Chance {
    private Double fraction;

    public Chance(Double fraction) {
        this.fraction = fraction;
        if (fraction > 1.0D) {
            this.fraction = 1.0D;
        }else if (fraction < 0.0D){
            this.fraction = 0.0D;
        }
    }

    public Double getFraction() {
        return fraction;
    }

    public Chance and(Chance anotherChance) {
        return new Chance(fraction * anotherChance.getFraction());
    }

    public Chance or(Chance anotherChance) {
        Double orResult = fraction + anotherChance.getFraction() - fraction*anotherChance.getFraction();
        return new Chance(orResult);
    }

    public Chance not() {
        return new Chance(1.0D - fraction);
    }
}
